name: fitness_advisor_chatbot
description: fitness_advisor_chatbot.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter: 
    sdk: flutter
    
  cupertino_icons: ^1.0.2 # Use with the CupertinoIcons class for iOS style icons.
  http: 1.1.0
  chat_bubbles: 1.6.0
  provider: 6.1.2
  mongo_dart: 0.10.0
  multi_dropdown: 3.0.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - lib/.flutter_env

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
          
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist/Urbanist-Thin.ttf
          weight: 200
        - asset: fonts/Urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: fonts/Urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: fonts/Urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: fonts/Urbanist/Urbanist-SemiBold.ttf
          weight: 600

    - family: MSReference2
      fonts:
        - asset: fonts/MSReference2/MSReference2-Regular.ttf
          weight: 400